# generated by appcreator
from django.conf.urls import url
from . import dal_views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^archiv-autocomplete/$',
        dal_views.ArchivAC.as_view(),
        name='archiv-autocomplete'
    ),
    url(
        r'^bibliography-autocomplete/$',
        dal_views.BibliographyAC.as_view(),
        name='bibliography-autocomplete'
    ),
    url(
        r'^glossary-autocomplete/$',
        dal_views.GlossaryAC.as_view(),
        name='glossary-autocomplete'
    ),
    url(
        r'^place-autocomplete/$',
        dal_views.PlaceAC.as_view(),
        name='place-autocomplete'
    ),
    url(
        r'^tablet-autocomplete/$',
        dal_views.TabletAC.as_view(),
        name='tablet-autocomplete'
    ),
]
