# Generated by Django 5.1.3 on 2025-02-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newsentry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsentry",
            options={
                "ordering": ["-updated"],
                "verbose_name": "News Entry",
                "verbose_name_plural": "News Entries",
            },
        ),
    ]
