# Generated by Django 3.2.7 on 2021-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='book',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='editor',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='journal',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Journal'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='pages',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='volume_nr',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Volume no.'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='pref_label',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Label'),
        ),
    ]
