# Generated by Django 3.2.7 on 2021-09-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_auto_20210921_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='related_objects',
            field=models.CharField(blank=True, help_text='tablets published', max_length=250, verbose_name='realted objects'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='related_publications',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='related_publications'),
        ),
        migrations.AddField(
            model_name='glossary',
            name='related_objects',
            field=models.IntegerField(blank=True, help_text='whatever', null=True, verbose_name='Related objects'),
        ),
        migrations.AddField(
            model_name='glossary',
            name='title',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='glossary',
            name='type',
            field=models.IntegerField(blank=True, help_text='whatever', null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='bibliography',
            field=models.CharField(blank=True, help_text='Bibliography', max_length=250, verbose_name='Bibliography'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='day',
            field=models.CharField(blank=True, help_text='Day of month', max_length=250, verbose_name='Babylonian Day'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='imported',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Imported (Person, date)'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='julian_date_year',
            field=models.IntegerField(blank=True, help_text='Year BCE', null=True, verbose_name='Year BCE'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='king',
            field=models.CharField(blank=True, help_text='King (abbreviated)', max_length=250, verbose_name='King'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='month',
            field=models.CharField(blank=True, help_text='Babylonian month (I-XII)', max_length=250, verbose_name='Babylonian Month'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='period',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='publication_name',
            field=models.CharField(blank=True, help_text='whatever', max_length=250, verbose_name='Publication name'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='year',
            field=models.CharField(blank=True, help_text='Regnal year', max_length=250, verbose_name='Babylonian Year'),
        ),
        migrations.AlterField(
            model_name='archiv',
            name='name',
            field=models.CharField(blank=True, help_text='following GMTR 1', max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='archiv',
            name='part_of',
            field=models.ForeignKey(blank=True, help_text='Place of issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_archiv_part_of_place', to='archiv.place', verbose_name='part of'),
        ),
        migrations.AlterField(
            model_name='archiv',
            name='related_objects',
            field=models.IntegerField(blank=True, help_text='tablet(s) related to archive', null=True, verbose_name='related objects'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='pref_label',
            field=models.CharField(blank=True, help_text='type of document', max_length=250, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='place',
            name='part_of',
            field=models.ForeignKey(blank=True, help_text='larger region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_place_part_of_place', to='archiv.place', verbose_name='part of'),
        ),
        migrations.AlterField(
            model_name='place',
            name='related_objects',
            field=models.IntegerField(blank=True, help_text='whatever', null=True, verbose_name='related objects'),
        ),
    ]
