# Generated by Django 3.2.7 on 2021-10-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_auto_20211004_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='related_bib_items',
            field=models.ManyToManyField(blank=True, help_text='whatever', to='archiv.Bibliography', verbose_name='Bib Item'),
        ),
        migrations.AlterField(
            model_name='place',
            name='related_tablets',
            field=models.ManyToManyField(blank=True, help_text='whatever', to='archiv.Tablet', verbose_name='related tablets'),
        ),
    ]
