# Generated by Django 3.2.7 on 2022-02-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0005_place_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="region",
        ),
    ]
