# Generated by Django 3.2.7 on 2021-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0006_auto_20211004_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiv',
            name='related_bib_items',
        ),
        migrations.RemoveField(
            model_name='archiv',
            name='related_tablets',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='related_bib_items',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='related_objects',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='related_tablets',
        ),
        migrations.RemoveField(
            model_name='glossary',
            name='related_bib_items',
        ),
        migrations.RemoveField(
            model_name='glossary',
            name='related_tablets',
        ),
        migrations.RemoveField(
            model_name='place',
            name='related_bib_items',
        ),
        migrations.RemoveField(
            model_name='place',
            name='related_tablets',
        ),
        migrations.AddField(
            model_name='bibliography',
            name='mentioned_archive',
            field=models.ManyToManyField(blank=True, help_text='whatever', related_name='rvn_bibliography_mentioned_archive_archiv', to='archiv.Archiv', verbose_name='Place mentioned on Tablet'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='mentioned_glossary_item',
            field=models.ManyToManyField(blank=True, help_text='mentioned_glossary_item', related_name='rvn_bibliography_mentioned_glossary_item_glossary', to='archiv.Glossary', verbose_name='mentioned_glossary_item'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='mentioned_place',
            field=models.ManyToManyField(blank=True, help_text='whatever', related_name='rvn_bibliography_mentioned_place_place', to='archiv.Place', verbose_name='Place mentioned on Tablet'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='key_word',
            field=models.ManyToManyField(blank=True, help_text='whatever', related_name='rvn_tablet_key_word_glossary', to='archiv.Glossary', verbose_name='random keyword'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='mentioned_archiv',
            field=models.ManyToManyField(blank=True, help_text='whatever', related_name='rvn_tablet_mentioned_archiv_archiv', to='archiv.Archiv', verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='mentioned_in_pub',
            field=models.ManyToManyField(blank=True, help_text='whatever', related_name='rvn_tablet_mentioned_in_pub_bibliography', to='archiv.Bibliography', verbose_name='Mentioned in Publication'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='mentioned_place',
            field=models.ManyToManyField(blank=True, help_text='whatever', related_name='rvn_tablet_mentioned_place_place', to='archiv.Place', verbose_name='Place mentioned on Tablet'),
        ),
    ]
