# Generated by Django 3.2.7 on 2021-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0007_auto_20211015_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossary',
            name='hierarchy',
        ),
        migrations.AddField(
            model_name='glossary',
            name='glossary_collection',
            field=models.CharField(blank=True, help_text='Collection to group Glossary entries', max_length=250, verbose_name='Collection'),
        ),
    ]
