# Generated by Django 3.2.7 on 2022-03-16 15:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0007_auto_20220310_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='paraphrase',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Tablet content', null=True, verbose_name='Paraphrase'),
        ),
    ]
