# Generated by Django 3.2.7 on 2021-11-05 09:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0008_auto_20211105_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={},
        ),
        migrations.RemoveField(
            model_name='glossary',
            name='type',
        ),
        migrations.AddField(
            model_name='glossary',
            name='broader_concept',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Concept with a broader meaning that this concept inherits from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrower_concepts', to='archiv.glossary', verbose_name='skos:broader'),
        ),
        migrations.AddField(
            model_name='glossary',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glossary',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glossary',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glossary',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
