# Generated by Django 3.2.7 on 2022-05-06 07:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0013_auto_20220427_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', ckeditor.fields.RichTextField(blank=True, default='Add brief introductory text')),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
