# Generated by Django 3.2.7 on 2022-05-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0014_introduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablet",
            name="key_word",
        ),
        migrations.RemoveField(
            model_name="tablet",
            name="mentioned_archiv",
        ),
    ]
