# Generated by Django 5.1.3 on 2024-11-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0017_alter_place_part_of"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archiv",
            options={
                "ordering": ["name"],
                "verbose_name": "Archiv",
                "verbose_name_plural": "Archivs",
            },
        ),
        migrations.AlterModelOptions(
            name="bibliography",
            options={
                "ordering": ["short_title"],
                "verbose_name": "Bibliography",
                "verbose_name_plural": "Bibliographies",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["name"],
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.AlterModelOptions(
            name="tablet",
            options={
                "ordering": ["id"],
                "verbose_name": "Tablet",
                "verbose_name_plural": "Tablets",
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="generic dossier name (change me!)",
                        help_text="whatever",
                        max_length=250,
                        verbose_name="Name of Dossier",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="whatever",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "archiv",
                    models.ForeignKey(
                        blank=True,
                        help_text="whatever",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="has_dossier",
                        to="archiv.archiv",
                        verbose_name="Archiv",
                    ),
                ),
            ],
        ),
    ]
