# Generated by Django 5.1.3 on 2024-11-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0018_alter_archiv_options_alter_bibliography_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dossier",
            options={
                "ordering": ["id"],
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="pleiades_url",
            field=models.URLField(
                blank=True,
                help_text="https://pleiades.stoa.org/",
                max_length=50,
                null=True,
                verbose_name="Pleiades URL",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                help_text="whatever",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_tablet_archiv_dossier",
                to="archiv.dossier",
                verbose_name="Dossier",
            ),
        ),
    ]
