# Generated by Django 5.1.3 on 2024-11-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0019_alter_dossier_options_place_pleiades_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiv",
            name="alt_name",
            field=models.CharField(
                blank=True,
                help_text="different name found in publications",
                max_length=250,
                verbose_name="Alternative name",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="author(s) of the publication",
                max_length=250,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="editor",
            field=models.CharField(
                blank=True,
                help_text="editor(s) of the publication",
                max_length=250,
                verbose_name="Editor",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="journal",
            field=models.CharField(
                blank=True,
                help_text="name of journal",
                max_length=250,
                verbose_name="Journal",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="pages",
            field=models.CharField(
                blank=True,
                help_text="pages in journal or sammelschrift",
                max_length=250,
                verbose_name="Pages",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="publication_year",
            field=models.CharField(
                blank=True,
                help_text="year in which it was published",
                max_length=250,
                verbose_name="Publication year",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="short_title",
            field=models.CharField(
                blank=True,
                help_text="abbreviated title according to Archiv für Orientforschung",
                max_length=250,
                verbose_name="Short Title",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="title of the publication",
                max_length=250,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="volume_nr",
            field=models.CharField(
                blank=True,
                help_text="issue of journal or series",
                max_length=250,
                verbose_name="Volume no.",
            ),
        ),
        migrations.AlterField(
            model_name="glossary",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="name of type of document",
                max_length=250,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lng",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="archiv",
            field=models.ForeignKey(
                blank=True,
                help_text="select corresponding archive",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_tablet_archiv_archiv",
                to="archiv.archiv",
                verbose_name="Archive",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                help_text="select corresponding dossier within archive",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_tablet_archiv_dossier",
                to="archiv.dossier",
                verbose_name="Dossier",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="museum_id",
            field=models.CharField(
                blank=True,
                help_text="Accession or collection number in museum",
                max_length=250,
                verbose_name="Museum No.",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NB", "nB"),
                    ("Each", "eAch"),
                    ("ENB", "enB"),
                    ("Ach", "lAch"),
                    ("-", "-"),
                ],
                default="-",
                help_text="select period in which the tablet was issued",
                max_length=250,
                verbose_name="Period",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="place_of_issue",
            field=models.ForeignKey(
                blank=True,
                help_text="select place of issue as specified on tablet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_tablet_place_of_issue_place",
                to="archiv.place",
                verbose_name="Place of issue",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="publication_name",
            field=models.CharField(
                blank=True,
                help_text="primary publication (abbreviation)",
                max_length=250,
                verbose_name="Publication name",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="text_number",
            field=models.CharField(
                blank=True,
                help_text="text number within primary publication",
                max_length=250,
                verbose_name="Text number",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="transliteration",
            field=models.TextField(
                blank=True,
                help_text="transliterated text or link to transliteration (achemenet.com)",
                null=True,
                verbose_name="Transliteration",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="type_content",
            field=models.ForeignKey(
                blank=True,
                help_text="select corresponding type of document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_tablet_type_content_glossary",
                to="archiv.glossary",
                verbose_name="Type and content",
            ),
        ),
    ]
