# Generated by Django 5.1.3 on 2024-11-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0021_tablet_inferred_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bibliography",
            name="book",
        ),
        migrations.RemoveField(
            model_name="bibliography",
            name="related_publications",
        ),
    ]
