# Generated by Django 5.1.3 on 2025-01-15 12:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0022_remove_bibliography_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiv",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                default="A short description of the archive",
                verbose_name="Archive Description",
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="intro_text",
            field=tinymce.models.HTMLField(
                blank=True, default="Add brief introductory text"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Add information on the location",
                null=True,
                verbose_name="Place description",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="paraphrase",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Tablet content",
                null=True,
                verbose_name="Paraphrase",
            ),
        ),
    ]
