# Generated by Django 5.1.3 on 2025-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0024_workpackage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workpackage",
            options={
                "ordering": ["id"],
                "verbose_name": "Work Package",
                "verbose_name_plural": "Work Packages",
            },
        ),
        migrations.AddField(
            model_name="tablet",
            name="work_package",
            field=models.ManyToManyField(
                blank=True,
                help_text="attribution of the tablet to one or more DigEanna Work Packages",
                null=True,
                related_name="related_tablets",
                to="archiv.workpackage",
                verbose_name="Work Packages",
            ),
        ),
    ]
