# Generated by Django 5.1.3 on 2025-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0025_alter_workpackage_options_tablet_work_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablet",
            name="work_package",
            field=models.ManyToManyField(
                blank=True,
                help_text="attribution of the tablet to one or more DigEanna Work Packages",
                related_name="related_tablets",
                to="archiv.workpackage",
                verbose_name="Work Packages",
            ),
        ),
    ]
