# Generated by Django 5.1.3 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0026_alter_tablet_work_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="remark",
            field=models.TextField(
                blank=True,
                help_text="general remarks regarding the content and attribution of the tablet to a dossier",
                null=True,
                verbose_name="Remarks",
            ),
        ),
    ]
