# Generated by Django 5.1.3 on 2025-01-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0027_tablet_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="regional_setting",
            field=models.ForeignKey(
                blank=True,
                help_text="select the inferred region where the content of the text is set, if there is no place of issue given",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_tablet_regional_setting_place",
                to="archiv.place",
                verbose_name="Regional setting",
            ),
        ),
    ]
