# Generated by Django 5.1.3 on 2025-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0029_vandrielfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="van_driel_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="choose the attribution of the text according to van Driel's categorization",
                related_name="related_tablets",
                to="archiv.vandrielfiles",
                verbose_name="file after G. van Driel",
            ),
        ),
    ]
