# Generated by Django 5.1.3 on 2025-02-06 16:36

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0031_tablet_private_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="change me",
                        help_text="name or type of the text form",
                        max_length=250,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "verbum_regens",
                    tinymce.models.HTMLField(
                        default="...",
                        help_text="verba regentia characteristic of and critical for the text form",
                        verbose_name="verbum regens",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="further notes and definition of the text form",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Form",
                "verbose_name_plural": "Text Forms",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="tablet",
            name="text_form",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable text form",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_tablet",
                to="archiv.textform",
                verbose_name="Text form",
            ),
        ),
    ]
