# Generated by Django 5.1.3 on 2025-02-06 16:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0032_textform_tablet_text_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="change me",
                        help_text="name of the type of purpose (as precise as possible in English)",
                        max_length=250,
                        verbose_name="Legal purpose",
                    ),
                ),
                (
                    "verbum_regens",
                    tinymce.models.HTMLField(
                        default="...",
                        help_text="verba regentia characteristic of and critical for the legal content of a text typ",
                        verbose_name="verbum regens",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="a brief description of the legal reality behind such a text",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Purpose",
                "verbose_name_plural": "Legal Purposes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="tablet",
            name="legal_purpose",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable legal purpose",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_tablet",
                to="archiv.legalpurpose",
                verbose_name="Legal Purpose",
            ),
        ),
    ]
