# Generated by Django 5.1.3 on 2025-02-07 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0033_legalpurpose_tablet_legal_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="change me",
                        help_text="designation of the type, whether transactional or not, outgoing, incoming etc.",
                        max_length=250,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="a brief description of the transaction type as viewed by the administration",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Type",
                "verbose_name_plural": "Transaction Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="tablet",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable transaction type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archiv.legalpurpose",
                verbose_name="Transaction Type",
            ),
        ),
    ]
