# Generated by Django 5.1.3 on 2025-02-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0034_transactiontype_tablet_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablet",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable transaction type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archiv.transactiontype",
                verbose_name="Transaction Type",
            ),
        ),
    ]
