# Generated by Django 5.1.3 on 2025-02-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0035_alter_tablet_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="change me",
                        help_text="concise designation of the domain",
                        max_length=250,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="a brief description of the textual domain in the economic and administrative reality of Eanna",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain (Eanna)",
                "verbose_name_plural": "Domains (Eanna)",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="tablet",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable transaction type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_tablet",
                to="archiv.transactiontype",
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable domain of the economic and administrative reality of Eanna",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_tablet",
                to="archiv.domain",
                verbose_name="Domain (Eanna)",
            ),
        ),
    ]
