# Generated by Django 5.1.3 on 2025-02-07 09:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0036_domain_alter_tablet_transaction_type_tablet_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="formatting",
            field=models.BooleanField(
                default=False,
                help_text="Is there any formatting in the text layout rather than simply scriptio continua?",
                verbose_name="Formatting",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="formatting_remarks",
            field=models.TextField(
                blank=True,
                help_text="Briefly describe any unusual or noteworthy points of text formatting",
                null=True,
                verbose_name="Formatting remarks",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="legacy_paraphrase",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="first paraphrase created for NaBuCCo of a text that has subsequently been reworked in a new paraphrase",
                null=True,
                verbose_name="Legacy paraphrase",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="sealings",
            field=models.BooleanField(
                default=False,
                help_text="Does the tablet have seal impressions?",
                verbose_name="Sealings",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="second_order_accounting",
            field=models.BooleanField(
                default=False,
                help_text="Does the text belong to or contain elements of second-order accounting, i.e. referring to other documents or similar?",
                verbose_name="second-order accounting",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="tablet_as_list",
            field=models.BooleanField(
                default=False,
                help_text="Is the text written as a list (rather than a single note)?",
                verbose_name="List",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="tablet_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("landscape", "landscape format"),
                    ("portrait", "portrait format"),
                    ("square", "square-shaped"),
                    ("unclear", "unclear format"),
                ],
                help_text="Choose the format of the physical tablet",
                max_length=100,
                null=True,
                verbose_name="Format of the Tablet",
            ),
        ),
    ]
