# Generated by Django 5.1.3 on 2025-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0037_tablet_formatting_tablet_formatting_remarks_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="introduction",
            options={
                "ordering": ["id"],
                "verbose_name": "Introduction",
                "verbose_name_plural": "Introductions",
            },
        ),
        migrations.AddField(
            model_name="tablet",
            name="labasi_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="https://labasi.acdh.oeaw.ac.at/",
                null=True,
                verbose_name="LaBaSi Identifier",
            ),
        ),
    ]
