# Generated by Django 5.1.3 on 2025-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0038_alter_introduction_options_tablet_labasi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="julian_date_day",
            field=models.IntegerField(
                blank=True,
                help_text="modern day (numbered) as calculated from the Babylonian date of issue",
                null=True,
                verbose_name="Day BCE",
            ),
        ),
        migrations.AddField(
            model_name="tablet",
            name="julian_date_month",
            field=models.IntegerField(
                blank=True,
                help_text="modern month (numbered) as calculated from the Babylonian date of issue",
                null=True,
                verbose_name="Month BCE",
            ),
        ),
    ]
