# Generated by Django 5.1.3 on 2025-03-03 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0039_tablet_julian_date_day_tablet_julian_date_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablet",
            name="julian_date_day",
            field=models.IntegerField(
                blank=True,
                help_text="modern day (numbered) as calculated from the Babylonian date of issue",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Day BCE",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="julian_date_month",
            field=models.IntegerField(
                blank=True,
                help_text="modern month (numbered) as calculated from the Babylonian date of issue",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Month BCE",
            ),
        ),
    ]
