# Generated by Django 5.1.3 on 2025-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0040_alter_tablet_julian_date_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archiv",
            options={
                "ordering": ["name"],
                "verbose_name": "Archive",
                "verbose_name_plural": "Archives",
            },
        ),
        migrations.AlterField(
            model_name="legalpurpose",
            name="verbum_regens",
            field=models.CharField(
                default="...",
                help_text="verba regentia characteristic of and critical for the legal content of a text typ",
                max_length=250,
                verbose_name="verbum regens",
            ),
        ),
        migrations.AlterField(
            model_name="textform",
            name="verbum_regens",
            field=models.CharField(
                default="...",
                help_text="verba regentia characteristic of and critical for the text form",
                max_length=250,
                verbose_name="verbum regens",
            ),
        ),
    ]
