# Generated by Django 5.1.3 on 2025-04-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0041_alter_archiv_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablet",
            name="tablet_as_list",
        ),
    ]
