# Generated by Django 5.1.3 on 2025-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0042_remove_tablet_tablet_as_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="direct_speech",
            field=models.BooleanField(
                default=False,
                help_text="Does the tablet quote any form of direct speech?",
                verbose_name="Features Direct Speech",
            ),
        ),
    ]
