# Generated by Django 5.2.5 on 2025-11-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0043_tablet_direct_speech"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactiontype",
            options={
                "ordering": ["name"],
                "verbose_name": "Transaction type",
                "verbose_name_plural": "Transaction types",
            },
        ),
        migrations.AddField(
            model_name="tablet",
            name="cleaned_text",
            field=models.TextField(
                blank=True,
                help_text="Used for searching",
                null=True,
                verbose_name="Internal field",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="short_title",
            field=models.CharField(
                blank=True,
                help_text="abbreviated title according to Archiv für Orientforschung",
                max_length=250,
                verbose_name="Short title",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="name",
            field=models.CharField(
                default="generic dossier name (change me!)",
                help_text="whatever",
                max_length=250,
                verbose_name="Name of dossier",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="cdli_no",
            field=models.CharField(
                blank=True,
                help_text="Link to CDLI",
                max_length=25,
                verbose_name="CDLI P-identifier",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="day",
            field=models.CharField(
                blank=True,
                help_text="Day of month",
                max_length=250,
                verbose_name="Babylonian day",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="direct_speech",
            field=models.BooleanField(
                default=False,
                help_text="Does the tablet quote any form of direct speech?",
                verbose_name="Features Direct speech",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="labasi_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="https://labasi.acdh.oeaw.ac.at/",
                null=True,
                verbose_name="LaBaSi identifier",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="legal_purpose",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable legal purpose",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_tablet",
                to="archiv.legalpurpose",
                verbose_name="Legal purpose",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="mentioned_in_pub",
            field=models.ManyToManyField(
                blank=True,
                help_text="whatever",
                related_name="rvn_tablet_mentioned_in_pub_bibliography",
                to="archiv.bibliography",
                verbose_name="Mentioned in publication",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="mentioned_place",
            field=models.ManyToManyField(
                blank=True,
                help_text="whatever",
                related_name="rvn_tablet_mentioned_place_place",
                to="archiv.place",
                verbose_name="Place mentioned on tablet",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="month",
            field=models.CharField(
                blank=True,
                help_text="Babylonian month (I-XII)",
                max_length=250,
                verbose_name="Babylonian month",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="museum_id",
            field=models.CharField(
                blank=True,
                help_text="Accession or collection number in museum",
                max_length=250,
                verbose_name="Museum no.",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="tablet_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("landscape", "landscape format"),
                    ("portrait", "portrait format"),
                    ("square", "square-shaped"),
                    ("unclear", "unclear format"),
                ],
                help_text="Choose the format of the physical tablet",
                max_length=100,
                null=True,
                verbose_name="Format of the tablet",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="text_number",
            field=models.CharField(
                blank=True,
                help_text="text number within primary publication",
                max_length=250,
                verbose_name="Text no.",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="transaction_type",
            field=models.ForeignKey(
                blank=True,
                help_text="select (one) attributable transaction type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="has_tablet",
                to="archiv.transactiontype",
                verbose_name="Transaction type",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="van_driel_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="choose the attribution of the text according to van Driel's categorization",
                related_name="related_tablets",
                to="archiv.vandrielfiles",
                verbose_name="File after G. van Driel",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="work_package",
            field=models.ManyToManyField(
                blank=True,
                help_text="attribution of the tablet to one or more DigEanna Work packages",
                related_name="related_tablets",
                to="archiv.workpackage",
                verbose_name="Work packages",
            ),
        ),
        migrations.AlterField(
            model_name="tablet",
            name="year",
            field=models.CharField(
                blank=True,
                help_text="Regnal year",
                max_length=250,
                verbose_name="Babylonian year",
            ),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="name",
            field=models.CharField(
                default="change me",
                help_text="designation of the type, whether transactional or not, outgoing, incoming etc.",
                max_length=250,
                verbose_name="Transaction type",
            ),
        ),
    ]
