# Generated by Django 5.2.5 on 2025-12-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0044_alter_transactiontype_options_tablet_cleaned_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='public',
            field=models.BooleanField(default=True, help_text='Set to false to make Tablet readable for logged in users', verbose_name='Tablet public'),
        ),
    ]
