# Generated by Django 5.2.5 on 2025-12-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0045_tablet_public'),
        ('infos', '0004_auto_20211112_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='project',
            field=models.ManyToManyField(blank=True, help_text='Select Project related to this tablet', related_name='tablets', to='infos.abouttheproject', verbose_name='Related Project(s)'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='public',
            field=models.BooleanField(default=True, help_text='Ucheck to make tablet readable only for logged in users', verbose_name='Published'),
        ),
    ]
