# Generated by Django 5.2.5 on 2025-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0046_tablet_project_alter_tablet_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavicoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='designation of the theme concerning the reality of slaves in a text', verbose_name='Theme')),
                ('description', models.TextField(blank=True, help_text='Description of the theme: what sphere of in life a slave does it pertain to? what is the historical significance?', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Theme (Navico)',
                'verbose_name_plural': 'Themes (Navico)',
                'ordering': ['theme'],
            },
        ),
    ]
