# Generated by Django 5.2.5 on 2025-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0047_navicotheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='navico_theme',
            field=models.ManyToManyField(blank=True, help_text="select the tablet's theme relating to Navico", related_name='related_tablets', to='archiv.navicotheme', verbose_name='Themes (Navico)'),
        ),
    ]
