# Generated by Django 5.2.5 on 2025-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0048_tablet_navico_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaveDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(help_text='designation of a specific descriptor used in a text for an oblate/slave', max_length=250, verbose_name='Oblate/Slave Descriptor')),
                ('description', models.TextField(blank=True, help_text='describe the significance of the descriptor', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Oblate/Slave Descriptor',
                'verbose_name_plural': 'Oblate/Slave Descriptors',
                'ordering': ['descriptor'],
            },
        ),
        migrations.CreateModel(
            name='SlaveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="designation of the slave's role in a text", max_length=250, verbose_name='Role')),
                ('description', models.TextField(blank=True, help_text='concisely describe the role and its significance in a text', null=True, verbose_name='Description')),
                ('active_passive', models.CharField(choices=[('active', 'active role'), ('passive', 'passive role'), ('ambiguous', 'ambiguous role')], default='active', help_text='Does the role pertain to an active or passive action in a text?', max_length=50, verbose_name='Active/Passive')),
            ],
            options={
                'verbose_name': 'Oblate/Slave Role',
                'verbose_name_plural': 'Oblate/Slave Roles',
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='tablet',
            name='slave_descriptor',
            field=models.ManyToManyField(blank=True, help_text='select the descriptors used for the oblate/slave', related_name='related_tablets', to='archiv.slavedescriptor', verbose_name='Slave descriptor'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='slave_role',
            field=models.ManyToManyField(blank=True, help_text='select the active/passive role of the oblate/slave featuring in the tablet', related_name='related_tablets', to='archiv.slaverole', verbose_name='Slave role'),
        ),
    ]
