# Generated by Django 5.2.5 on 2025-12-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0049_slavedescriptor_slaverole_tablet_slave_descriptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='King',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cyr', help_text='Traditional (usually biblical) name of the king', max_length=250, verbose_name='King')),
                ('alt_name', models.CharField(blank=True, help_text='The name(s) of the king as it would be in the original language(s) of the texts.', max_length=250, null=True, verbose_name='Names')),
                ('abbreviation', models.CharField(default='Cyr', help_text="Abbreviation of the king's name as it should show up in the date formula", max_length=50, verbose_name='Abbreviation')),
                ('begin_of_reign', models.IntegerField(default=1, help_text='The year BC in which a king took up reign.', verbose_name='Beginning of reign')),
                ('end_of_reign', models.IntegerField(blank=True, help_text="The year BC in which a king's reign ended.", null=True, verbose_name='Ending of reign')),
                ('description', models.TextField(blank=True, help_text="Describe what characterized the king's reign in Babylonia", null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'King',
                'verbose_name_plural': 'Kings',
                'ordering': ['begin_of_reign'],
            },
        ),
        migrations.AddField(
            model_name='tablet',
            name='related_king',
            field=models.ForeignKey(blank=True, help_text='King', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_tablet', to='archiv.king', verbose_name='King'),
        ),
    ]
