# Generated by Django 5.2.5 on 2025-12-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0050_king_tablet_related_king'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablet',
            name='king',
        ),
    ]
