# Generated by Django 6.0.4 on 2026-08-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0051_remove_tablet_king'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the period, e.g. Neo-Babylonian', max_length=250, verbose_name='Period name')),
                ('abbreviation', models.CharField(help_text='Period abbreviation, e.g. nB', max_length=250, verbose_name='Abbreviation')),
                ('beginning', models.CharField(help_text='The year or century BC of the start of the period', max_length=250, verbose_name='Beginning of period')),
                ('ending', models.CharField(help_text='The year or century BC of the end of the period', max_length=250, verbose_name='End of period')),
                ('description', models.CharField(help_text='Describe characteristics, notable events of the period, its start, or end', max_length=250, verbose_name='End of period')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='tablet',
            name='type_content',
            field=models.ForeignKey(blank=True, help_text='select corresponding type of document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_tablet_type_content_glossary', to='archiv.glossary', verbose_name='Type and content (legacy)'),
        ),
    ]
