# Generated by Django 6.0.4 on 2026-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0052_periodobject_alter_tablet_type_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodobject',
            name='description',
            field=models.TextField(help_text='Describe characteristics, notable events of the period, its start, or end', max_length=250, verbose_name='Description'),
        ),
    ]
