# Generated by Django 6.0.4 on 2026-08-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0053_alter_periodobject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='king',
            name='period_object',
            field=models.ForeignKey(blank=True, help_text='select period related to the king', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_king', to='archiv.periodobject', verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='period_object',
            field=models.ForeignKey(blank=True, help_text='select period in which the tablet was issued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_tablet', to='archiv.periodobject', verbose_name='Period'),
        ),
    ]
