# Generated by Django 6.0.4 on 2026-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0054_king_period_object_tablet_period_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodobject',
            name='beginning',
            field=models.CharField(blank=True, help_text='The year or century BC of the start of the period', max_length=250, null=True, verbose_name='Beginning of period'),
        ),
        migrations.AlterField(
            model_name='periodobject',
            name='description',
            field=models.TextField(blank=True, help_text='Describe characteristics, notable events of the period, its start, or end', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='periodobject',
            name='ending',
            field=models.CharField(blank=True, help_text='The year or century BC of the end of the period', max_length=250, null=True, verbose_name='End of period'),
        ),
    ]
