# Generated by Django 3.1.5 on 2021-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infos", "0002_auto_20210921_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abouttheproject",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectinst",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
