# Generated by Django 3.2.7 on 2021-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infos", "0003_auto_20211110_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abouttheproject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectinst",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
