# Generated by Django 5.2.5 on 2025-12-15 10:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20211112_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttheproject',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Project Description'),
        ),
    ]
