# Generated by Django 5.2.5 on 2025-12-15 10:00

from django.db import migrations


def forwards_func(apps, schema_editor):
    AboutTheProject = apps.get_model("infos", "AboutTheProject")
    AboutTheProject.objects.get_or_create(
        title="Nabucco",
    )
    AboutTheProject.objects.get_or_create(
        title="DigEanna",
    )
    AboutTheProject.objects.get_or_create(
        title="Navico",
    )


def backwards_func(apps, schema_editor):
    print("foo")


class Migration(migrations.Migration):
    dependencies = [
        ("infos", "0005_alter_abouttheproject_description"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
